### ISSUE TITLE
Realizar Plano de Integração para login com o Gov.br 

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/IdentidadeUnicaDeSaude#69]
### Objetivo
**Como** gestor do Mapa
**Quero** realizar integração com a base de dados do Gov.br
**Para** realizar a validação de CPF dos agentes ao se cadastrarem

### Contexto
Atualmente um usuário ao se cadastrar no Mapa, por meio do ID Saúde, não ocorre nenhuma validação pelo sistema do CPF inserido, se ele existe ou não, ou se já está cadastrado junto ao Mapa. Portanto, é necessário que ocorra essa validação, por meio da integração com a base de dados do Gov.br

### Escopo
Realizar estudo inicial para identificar como implementar uma integração da base de dados do Gov.br com a base de dados do mapa da Saúde, para que quando um usuário faça seu cadastro na plataforma, então seja feita uma validação automática do CPF inserido no ID Saúde.

**Sugestões para análise e estudo:**

### Observações
Verificar no site do Gov.br
Incluir referências do Gov.br

### Roadmap

- [ ] Preenchimento do [Plano de Integração](https://manual-roteiro-integracao-login-unico.servicos.gov.br/pt/stable/arquivos/Modelo_PlanodeIntegracao_LOGINUNICO_Versao-4.doc). Leia atentamente as instruções de preenchimento que constam no próprio documento
    - [x] Preenchimento básico dos dados da instituição
    - [x] 1. Informações gerais do (s) Sistema (s) e dos Serviço (s) para Integração (Obrigatório)
    - [x] Características de Acesso ao Serviço (definições de serviços) - (Serviço, Número de acessos por dia, Picos de acessos ou momentos de alta demanda do serviço, Quantidade atual de contas de acesso dos serviços)
    - [x] 1.2. Responsável pela integração (Obrigatório)
    - [x] 1.3. Ações/Cronograma (Obrigatório)
    - [x] 2. Informações Técnicas para Cadastro do Sistema ao Login Único
         - Ambiente de homologação
             - [x] Listas de IPs: são referentes aos Gateways ou elemento de rede. Deverão ser informados os IPs (Internet Protocol) dos servidores de internet (Gateway) usados para permitir o acesso à internet, pois deverão ser cadastrados nos sistemas de firewall do SERPRO para autorizar a recepção de requisições advindas da rede de computadores do Órgão;
             - [x] Nome da Apresentação do Serviço / Sistema no Login Único: Nome será mostrado ao cidadão no momento que realizar primeira autenticação (tela de autorização. Deverá ter até 50 caracteres. Item obrigatório;
             - [x] Níveis, Categorias e Selos: Informar quais níveis, categorias e selos de confiabilidade serão utilizados pela aplicação para confirmar acesso. Essa informação pode ser verificada em https://manual-roteiro-integracao-login-unico.servicos.gov.br/pt/stable/catalogoconfiabilidades.html#niveis-de-autenticacao-selos-e-catalogo-de-confiabilidades
             - [x] URL(s) de retorno: a página do serviço / sistema que será exibida após autenticação com sucesso do Login Único. Podem ser várias URLs. Item Obrigatório;
             - [x] URL para imagem da identificação do Sistema / Serviço: imagem pública na internet com configuração de largura e altura: 70 pixels. Permite apenas 1(um) URL da Imagem. Item opcional.
             - [x] URL para página inicial do Sistema / Serviço: página inicial onde estará botão de acesso ao Login Único. Permite apenas 1(um) URL. Item Obrigatório.
             - [x] URL(s) de Log Out: a página do serviço / Sistema que será exibida após cidadão finalizar sessão de login. Item Obrigatório. Uma mesma URL de logout NÃO pode ser usada em mais de um CLIENT_ID.
         - Ambiente de produção
             - [x] Listas de IPs: são referentes aos Gateways ou elemento de rede. Deverão ser informados os IPs (Internet Protocol) dos servidores de internet (Gateway) usados para permitir o acesso à internet, pois deverão ser cadastrados nos sistemas de firewall do SERPRO para autorizar a recepção de requisições advindas da rede de computadores do Órgão;
             - [x] Nome da Apresentação do Serviço / Sistema no Login Único: Nome será mostrado ao cidadão no momento que realizar primeira autenticação (tela de autorização. Deverá ter até 50 caracteres. Item obrigatório;
             - [x] Níveis, Categorias e Selos: Informar quais níveis, categorias e selos de confiabilidade serão utilizados pela aplicação para confirmar acesso. Essa informação pode ser verificada em https://manual-roteiro-integracao-login-unico.servicos.gov.br/pt/stable/catalogoconfiabilidades.html#niveis-de-autenticacao-selos-e-catalogo-de-confiabilidades
             - [x] URL(s) de retorno: a página do serviço / sistema que será exibida após autenticação com sucesso do Login Único. Podem ser várias URLs. Item Obrigatório;
             - [x] URL para imagem da identificação do Sistema / Serviço: imagem pública na internet com configuração de largura e altura: 70 pixels. Permite apenas 1(um) URL da Imagem. Item opcional.
             - [x] URL para página inicial do Sistema / Serviço: página inicial onde estará botão de acesso ao Login Único. Permite apenas 1(um) URL. Item Obrigatório.
             - [x] URL(s) de Log Out: a página do serviço / Sistema que será exibida após cidadão finalizar sessão de login. Item Obrigatório. Uma mesma URL de logout NÃO pode ser usada em mais de um CLIENT_ID.
- [x] Geração da Chave PGP - A chave PGP é solicitada para transmissão das credenciais de forma segura. Informações sobre como [administrar as chaves PGP para credenciais do Login Único](https://manual-roteiro-integracao-login-unico.servicos.gov.br/pt/stable/chavepgp.html).
- [ ] 3. Assinaturas (Responsável pelo Serviço no Órgão, Responsável pela Implementação da Integração da Área de Tecnologia)
- [x] Documento e chaves devem ser encaminhados por email
- [x] A chamada para autenticação deverá ocorrer pelo botão com o conteúdo Entrar com GOV.BR. Para o formato do botão, seguir as orientações do [Design System do Governo Federal](https://dsgov.estaleiro.serpro.gov.br/components/signin?tab=designer)

### Assinaturas

1. Utilizar endereço para processo de assinatura: https://assinador.iti.br/
2. Um dos assinantes deverá fazer o procedimento primeiro, e posteriormente o outro
3. Uma vez que o documento esteja pronto, gerar o pdf dele, logar no assinador, através de sua conta Gov.br, com pelo menos nível prata (reconhecimento facial)
4. Efetuar assinatura por meio do assinador, e baixar pdf já assinado para que o outro possa realizar sua assinatura em cima da nova versão, já assinada.

Ver tutorial a seguir:
https://www.youtube.com/watch?v=bw46fzVfKPM
